spring:
  profiles:
    include: auth, cloud, datasource

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

  flyway:
    enabled: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
